# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Teoj9cZjDLw4HOWRiSMLWUvPAjbdXiix
"""

import time
class calculator():
    def __init__(self):
      f = open('Calculator_constrcutor.txt', 'r')
      content = f.read()
      print(content)
      f.close()
      history=open('history.txt','w')
      history.write("")
      
    def add(self,a,b):
      start=time.clock()
      result=a+b
      end=time.clock()
      t=repr(end - start)
      a=repr(a)
      b=repr(b)
      r=repr(result)
      history=open('history.txt','a')
      str="- time : "+t+"| action : add  "+a+","+b+"|result : "+r+"\n"
      history.write(str)
      return result
    def multiply(self,a,b):
      start=time.clock()
      result=a*b
      end=time.clock()
      t=repr(end - start)
      a=repr(a)
      b=repr(b)
      r=repr(result)
      str="- time : "+t+"| action : multiply  "+a+","+b+"|result : "+r+"\n"
      history=open('history.txt','a')
      history.write(str)
      return result
    def divide(self,a,b):
      start=time.clock()
      result=a/b
      end=time.clock()
      t=repr(end - start)
      a=repr(a)
      b=repr(b)
      r=repr(result)
      str="- time : "+t+"| action : divide  "+a+","+b+"|result : "+r+"\n"
      history=open('history.txt','a')
      history.write(str)
      return result
    def subtract(self,a,b):
      start=time.clock()
      result=a-b
      end=time.clock()
      t=repr(end - start)
      a=repr(a)
      b=repr(b)
      r=repr(result)
      str="- time : "+t+"| action : subtract  "+a+","+b+"|result : "+r+"\n"
      history=open('history.txt','a')
      history.write(str)
      return result
    def history(self):
      history = open('history.txt', 'r')
      content = history.read()
      print(content)
      history.close()